apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[\n  {\n    \"apiVersion\": \"operator.apps.openshift.io/v1\",\n    \"kind\": \"RunOnceDurationOverride\",\n    \"metadata\": {\n      \"name\": \"cluster\"\n    },\n    \"spec\": {\n      \"podResourceOverride\": {\n        \"spec\": {\n          \"activeDeadlineSeconds\": 3600\n        }\n      }\n    }\n  }\n]"
    capabilities: Seamless Upgrades
    categories: OpenShift Optional
    certifiedLevel: Primed
    olm.skipRange: ">=4.3.0 <4.13.0"
    containerImage: quay.io/openshift/runoncedurationoverride-rhel8-operator:4.13
    createdAt: 2019/11/15
    description: An operator to manage the OpenShift RunOnceDurationOverride Mutating Admission Webhook Server
    healthIndex: B
    repository: https://github.com/openshift/run-once-duration-override-operator
    support: Red Hat
  labels:
    operatorframework.io/arch.amd64: supported
  name: runoncedurationoverride-operator.v4.13.0
  namespace: runoncedurationoverride-operator
spec:
  customresourcedefinitions:
    owned:
      - description: Represents an instance of RunOnceDurationOverride Admission Webhook
        displayName: RunOnceDurationOverride
        kind: RunOnceDurationOverride
        name: runoncedurationoverride.operator.apps.openshift.io
        version: v1
  description: ""
  displayName: RunOnceDurationOverride Operator
  install:
    strategy: deployment
    spec:
      permissions:
      - rules:
        # to have the power to ensure RBAC for the operand
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - roles
            - rolebindings
          verbs:
            - create
            - update
            - patch
            - get

        # to have the power to watch secondary resources
        - apiGroups:
            - ''
          resources:
            - configmaps
            - secrets
            - services
            - serviceaccounts
            - pods
          verbs:
            - get
            - create
            - update
            - patch
            - list
            - watch

        # to have the power to watch secondary resources
        - apiGroups:
            - apps
          resources:
            - daemonsets
            - deployments
          verbs:
            - create
            - get
            - update
            - patch
            - list
            - watch
        serviceAccountName: runoncedurationoverride-operator
      clusterPermissions:
      - rules:
        # to have the power to create 'RoleBinding' that refs extension-apiserver-authentication-reader
        # in kube-system namespace.
        # to give the operand power to read the config for terminating authentication.
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - rolebindings
          verbs:
            - create
            - update
            - patch
            - get
        # Operator must have these privs so that it can grant them to the operand
        - apiGroups:
            - flowcontrol.apiserver.k8s.io
          resources:
            - flowschemas
            - prioritylevelconfigurations
          verbs:
            - get
            - list
            - watch

        # to have the power to read configmaps in the kube-system namespace
        - apiGroups:
            - ''
          resources:
            - configmaps
          verbs:
            - get
            - list
            - watch

        # to have the power to ensure RBAC for the operand
        - apiGroups:
            - rbac.authorization.k8s.io
          resources:
            - clusterroles
            - clusterrolebindings
          verbs:
            - create
            - update
            - patch
            - get

        # to have the power to reconcile request(s)
        - apiGroups:
            - operator.apps.openshift.io
          resources:
            - runoncedurationoverrides
            - runoncedurationoverrides/status
            - runoncedurationoverrides/finalizers
          verbs:
            - update
            - get
            - list
            - watch

        # to have the power to manage configuration for admission webhook
        - apiGroups:
            - admissionregistration.k8s.io
          resources:
            - mutatingwebhookconfigurations
          verbs:
            - create
            - update
            - patch
            - delete
            - list
            - watch

        # to have the power to manage APIService object(s)
        - apiGroups:
            - apiregistration.k8s.io
          resources:
            - apiservices
          verbs:
            - create
            - update
            - patch
            - get
            - list
            - watch

        # to grant the operand power to create admission reviews
        - apiGroups:
            - apps.openshift.io
          resources:
            - runoncedurationoverride
          verbs:
            - create

        # default for an aggregated apiserver
        - apiGroups:
            - admissionregistration.k8s.io
          resources:
            - validatingwebhookconfigurations
            - mutatingwebhookconfigurations
          verbs:
            - get
            - list
            - watch

        # to grant power to the operand to watch Namespace(s)
        - apiGroups:
            - ""
          resources:
            - namespaces
          verbs:
            - get
            - list
            - watch

        # to grant power to the operand to delegate authentication and authorization
        - apiGroups:
            - authentication.k8s.io
          resources:
            - tokenreviews
          verbs:
            - create
        - apiGroups:
            - authorization.k8s.io
          resources:
            - subjectaccessreviews
          verbs:
            - create

        # to grant power to the operand to use hostnetwork-v2 scc
        - apiGroups:
            - security.openshift.io
          resources:
            - securitycontextconstraints
          verbs:
            - use
          resourceNames:
            - hostnetwork-v2

        # to grant power to the operand to allow anonymous access to the admission server
        - apiGroups:
            - admission.apps.openshift.io
          resources:
            - runoncedurationoverrides
          verbs:
            - create
            - get
        serviceAccountName: runoncedurationoverride-operator
      deployments:
        - name: runoncedurationoverride-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                runoncedurationoverride.operator: "true"
            template:
              metadata:
                name: runoncedurationoverride
                labels:
                  runoncedurationoverride.operator: "true"
              spec:
                serviceAccountName: runoncedurationoverride-operator
                containers:
                  - name: runoncedurationoverride-operator
                    image: quay.io/openshift/runoncedurationoverride-rhel8-operator:4.13
                    imagePullPolicy: Always
                    command:
                      - /usr/bin/run-once-duration-override-operator
                    args:
                      - "start"
                      - "--namespace=$(OPERAND_NAMESPACE)"
                      - "--v=2"
                    env:
                      - name: OPERATOR_POD_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: OPERAND_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: OPERAND_IMAGE
                        value: quay.io/openshift/runoncedurationoverride-rhel8:4.13
                      - name: OPERAND_VERSION
                        value: 1.0.0
                    ports:
                      - containerPort: 8080
                    readinessProbe:
                      httpGet:
                        path: /healthz
                        port: 8080
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8080
                      initialDelaySeconds: 5
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                        - ALL
                securityContext:
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - activeDeadlineSeconds
  labels:
    olm-owner-enterprise-app: runoncedurationoverride-operator
    olm-status-descriptors: runoncedurationoverride-operator.v4.13.0
  maintainers:
    - email: support@redhat.com
      name: Red Hat
  provider:
    name: Red Hat
  version: 4.13.0
