apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: run-once-duration-override-operator
  namespace: run-once-duration-override-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: run-once-duration-override-operator
subjects:
  - kind: ServiceAccount
    name: run-once-duration-override-operator
    namespace: run-once-duration-override-operator
