apiVersion: apps/v1
kind: Deployment
metadata:
  name: runoncedurationoverride-operator-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      registry.operator.runoncedurationoverride: "true"
  template:
    metadata:
      labels:
        registry.operator.runoncedurationoverride: "true"
      name: runoncedurationoverride-operator-registry
    spec:
      initContainers:
      - name: mutate-csv-and-generate-sqlite-db
        image: RUNONCEDURATIONOVERRIDE_OPERATOR_REGISTRY_IMAGE
        imagePullPolicy: Always
        command:
        - sh
        args:
        - /scripts/registry-init.sh
        envFrom:
        - configMapRef:
            name: runoncedurationoverride-operator-registry-env
        volumeMounts:
        - name: workdir
          mountPath: /bundle
      containers:
      - name: runoncedurationoverride-operator-registry
        image: RUNONCEDURATIONOVERRIDE_OPERATOR_REGISTRY_IMAGE
        imagePullPolicy: Always
        command:
        - /usr/bin/registry-server
        - --database=/bundle/bundles.db
        volumeMounts:
        - name: workdir
          mountPath: /bundle
        ports:
        - containerPort: 50051
          name: grpc
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=localhost:50051
        readinessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=localhost:50051
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: workdir
        emptyDir: {}
